"""
Functions shared between data processing scripts
"""

import sys
import operator

def parse_removal_list_from_file(input_file):
    remove_list = []
    try:
        fp = open(input_file, 'r')
    except IOError:
        sys.exit("Could not open file: {}".format(input_file))

    for line in fp.readlines():
        # this has to be a tuple, so we can hash it later
        remove_group = tuple(line.strip().split(' '))
        remove_list.append(remove_group)

    fp.close()
    return remove_list

def read_mapping(mapping_file):
    """ Read (gene ID) -> (gene symbol) mapping file into a dict """
    mapping_hash = {}
    try:
        fp = open(mapping_file, "r")
    except IOError:
        sys.exit("Error opening file {}".format(mapping_file))

    for line in fp.readlines():
        info = line.split()
        mapping_hash[info[0]] = info[1]

    fp.close()
    return mapping_hash


def read_seed(seed_file, seed_number, seed_hash):
    """ Read seed file into a list containing sublists representing each seed """
    try:
        fp = open(seed_file, "r")
    except IOError:
        sys.exit("Error opening file {}".format(seed_file))

    seed_hash[seed_number] = []
    for line in fp.readlines():
        info = line.split()
        seed_hash[seed_number].append(info[1])

    fp.close()
    return seed_hash


def read_rwr(prediction_file, seed_hash, seed_number):
    """ Read RWR results file (generated by multi_matrix.py) into a dict.

    NOTE that this function also removes results that are in the current
    seed (since they aren't informative, for our purposes).

    seed_hash: maps (gene ID) -> (ranking number)
    """
    ranking_hash = {}

    try:
        fp = open(prediction_file, "r")
    except IOError:
        sys.exit("Error opening file {}".format(prediction_file))

    # start rankings from 1, rather than 0
    index = 1
    for line in fp.readlines():
        # for now, filter out everything in all seeds
        # this should probably be generalized somehow
        if line.strip() not in seed_hash[seed_number]:
            ranking_hash[line.strip()] = index
            index += 1

    fp.close()
    return ranking_hash

def generate_sorted_gene_list(prediction_file, gene_rank, seed_no,
                              tissue_id, seed_hash):
    """ Gets a list of (gene, rank) tuples, sorted by rank """
    if seed_no not in gene_rank:
        gene_rank[seed_no] = {}

    gene_rank[seed_no][tissue_id] = read_rwr(prediction_file,
                                             seed_hash,
                                             seed_no)
    filtered_genes = [(g, r) for g, r
                      in gene_rank[seed_no][tissue_id].iteritems()]

    sorted_genes = sorted(filtered_genes, key=lambda x: x[1])
    return sorted_genes
